// <auto-generated />
using System;
using Inmobiliaria.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inmobiliaria.Migrations
{
    [DbContext(typeof(InmobiliariaDatabaseContext))]
    [Migration("20201118231635_MigracionConFormulario")]
    partial class MigracionConFormulario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inmobiliaria.Models.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("mensaje");

                    b.Property<string>("nombre");

                    b.Property<string>("telefono");

                    b.Property<string>("tipoContacto");

                    b.Property<int>("tipoOperacion");

                    b.HasKey("Id");

                    b.ToTable("Formularios");
                });

            modelBuilder.Entity("Inmobiliaria.Models.Inmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ambientes");

                    b.Property<int>("banos");

                    b.Property<string>("barrio");

                    b.Property<int>("cochera");

                    b.Property<string>("descripcion");

                    b.Property<string>("direccion");

                    b.Property<string>("imagen");

                    b.Property<float>("precio");

                    b.HasKey("Id");

                    b.ToTable("Inmuebles");
                });

            modelBuilder.Entity("Inmobiliaria.Models.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidadDeVisitas");

                    b.Property<string>("fechaDePublicacion");

                    b.Property<int?>("inmuebleId");

                    b.Property<int>("miIdInmuebe");

                    b.Property<int>("operacion");

                    b.HasKey("Id");

                    b.HasIndex("inmuebleId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("Inmobiliaria.Models.Publicacion", b =>
                {
                    b.HasOne("Inmobiliaria.Models.Inmueble", "inmueble")
                        .WithMany()
                        .HasForeignKey("inmuebleId");
                });
#pragma warning restore 612, 618
        }
    }
}
